### ISSUE TITLE
As an online store, I want to provide verifiable receipts for purchases, so that customers can confirm the details of their transactions and have documented evidence for warranty claims, returns, or expense tracking.

### ISSUE THREAD

**Issue by aleksijalmanen** [stekki/ssi-wallet#22]
Acceptance criteria:

- [ ] The mock store is able to provide verifiable credentials as receipts
- [ ] The users are able to pass on the receipt credentials when reselling said object
- [ ] The passed on receipt should retain the critical details from the initial point of purchase
